runtime: php55
api_version: 1

handlers:
- url: /site\.css
  script: site.css


- url: /
  script: index.html

- url: /index\.html
  script: index.html

- url: /contact\.html
  script: contact.html

- url: /about-me\.html
  script: about-me.html

- url: /projects\.html
  script: projects.html

- url: /resume\.html
  script: resume.html

- url: /Projects/branch\.html
  script: Projects/branch.html

- url: /Projects/cache\.html
  script: Projects/cache.html

- url: /Projects/closed-server\.html
  script: Projects/closed-server.html

- url: /Projects/disk\.html
  script: Projects/disk.html

- url: /Projects/graph\.html
  script: Projects/graph.html

- url: /Projects/inheritance\.html
  script: Projects/inheritance.html

- url: /Projects/interactive\.html
  script: Projects/interactive.html

- url: /Projects/interpreter\.html
  script: Projects/interpreter.html

- url: /Projects/newton\.html
  script: Projects/newton.html

- url: /Projects/op-overloading\.html
  script: Projects/op-overloading.html

- url: /Projects/open-server\.html
  script: Projects/open-server.html

- url: /Projects/operating-system\.html
  script: Projects/operating-system.html

- url: /Projects/pca\.html
  script: Projects/pca.html

- url: /Projects/tree\.html
  script: Projects/tree.html

- url: /Projects/images
  static_dir: /Projects/images

- url: /Projects/zip_files
  static_dir: /Projects/zip_files