runtime: php55
api_version: 1

handlers:
- url: /site.css
  static_files: site.css
  upload: site.css
  
- url: /
  script: index.html

- url: /index\.html
  script: index.html

- url: /contact\.html
  script: contact.html

- url: /about-me\.html
  script: about-me.html

- url: /projects\.html
  script: projects.html

- url: /resume\.html
  script: resume.html

- url: /hire-me\.php
  script: hire-me.php

- url: /thankyou\.php
  script: thankyou.php

- url: /Projects
  static_dir: Projects

- url: /logos
  static_dir: logos

- url: /animations\.js
  script: animations.js

- url: /DaquiganResume\.pdf
  static_files: DaquiganResume.pdf
  upload: DaquiganResume.pdf

- url: /DaquiganResume\.docx
  static_files: DaquiganResume.docx
  upload: DaquiganResume.docx

env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/ddaquigan-188101:us-west1:portfolio-db;dbname=guestbook
  MYSQL_USER: root
  MYSQL_PASSWORD: password