runtime: php55
api_version: 1

handlers:
- url: /site.css
  static_files: site.css
  upload: site.css
  
- url: /
  script: index.html

- url: /index\.html
  script: index.html

- url: /contact\.html
  script: contact.html

- url: /about-me\.html
  script: about-me.html

- url: /projects\.html
  script: projects.html

- url: /resume\.html
  script: resume.html

- url: /hire-me\.html
  script: hire-me.html

- url: /thank-you\.php
  script: thank-you.php

- url: /Projects
  static_dir: Projects

- url: /logos
  static_dir: logos

- url: /animations\.js
  script: animations.js

- url: /DaquiganResume\.pdf
  static_files: DaquiganResume.pdf
  upload: DaquiganResume.pdf

- url: /DaquiganResume\.docx
  static_files: DaquiganResume.docx
  upload: DaquiganResume.docx

env_variables:
  MYSQL_DSN: 'mysql:host=localhost;dbname=responses'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: ''

beta_settings:
      cloud_sql_instances: 'ddaquigan-188101:us-west1:portfolio-instance'